### ISSUE TITLE
GHA CI: add commit hash to artifacts filename

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Mobsub#2]
Projects that can be referenced:

https://github.com/qwerttvv/Player
https://github.com/zhongfly/mpv-winbuild

Update: I looked into another project I am familiar with and explored based on their workflow files and it looks good. I will create a pull request.

**Comment by MIRIMIRIM** [comment]
Why add commit hash to the file name? You can see commit on GHA webpage, and locally, you can use `Ikkoku --version` to view the commit hash.

**Comment by 3gf8jv4dv** [comment]
> Why add commit hash to the file name? You can see commit on GHA webpage, and locally, you can use `Ikkoku --version` to view the commit hash.

I know these ways of viewing versions.

My initial thought was that if there is a new commit in the future that triggers an automatic build, it can be distinguished from the old version. I have the habit of storing binary files of some software so that I can visually show that the version of the file has changed. Some other projects I have seen do this.

If you don’t like it, you can close the issue and pull request.

**Comment by 3gf8jv4dv** [comment]
@MIRIMIRIM 

I thought about it and it seems that my previous description was not very clear. I want to add the commit hash only for the packaged archive file name (similar to the binary file in Releases), not the executable file itself. Is this something you misunderstood?

**Comment by MIRIMIRIM** [comment]
> @MIRIMIRIM
> 
> I thought about it and it seems that my previous description was not very clear. I want to add the commit hash only for the packaged archive file name (similar to the binary file in Releases), not the executable file itself. Is this something you misunderstood?

No misunderstanding, as I download and delete the packages afterward, so...
